version: "3"
services:
  api:
    build:
      context: apiservice
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - api
      - prometheus_exporter

  prometheus_exporter:
    build:
      context: ./prometheus_exporter
    ports:
      - "8080:8080"
    command: redis
    links:
      - redis
