name: Deploy App in Development ENV

on:
  push:
    branches:
      - main

jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Short Hash
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Set Docker tag Name
        id: tag
        run: echo "::set-output name=docker_tag::"${GITHUB_REF_NAME/\//"-"}""

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./apiservice
          file: Dockerfile
          tags: akshayaaa/inmemory_keyval_server:${{ steps.tag.outputs.docker_tag }}-${{ steps.vars.outputs.sha_short }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
